apiVersion: v1
kind: Service
metadata:
  name: spring-crud-svc
spec:
  type: NodePort
  selector:
    crud: spring
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30030
      targetPort: 8080    
